server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    relabel_configs:
      - source_labels: ["__path__"]
        regex: ".*/containers/([0-9a-f]{64})/.*"
        target_label: "container"
    static_configs:
      - targets: ["localhost"]
        labels:
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            component: component
            channel: channel
            pipeline_version: pipeline_version
            schema_version: schema_version
            assignment_id: assignment_id
            event: event
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:
          component:
          channel:
          pipeline_version:
          schema_version:
